app = "react-kanban-tool"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"

[[services]]
  internal_port = 4173
  protocol = "tcp"
  request_timeout = "30s"
  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["http", "tls"]
    port = 443
  [services.concurrency]
    type = "requests"
    soft_limit = 15
    hard_limit = 25
  [[services.tcp_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "1m"
